### ISSUE TITLE
Cannot find module 'lodash/assign'

### ISSUE THREAD

**Issue by maximilianmeier** [theoomoregbee/sails-hook-swagger-generator#88]
After installing the module with npm I get this error. I could fix it by going into the node_modules folder of this package and running npm install. But on our CI system this trick does not work.

Is there something missing i have to to or is this an issue? If so, a proper fix would be appreciated.

This is the error log I get.

```
error: Failed to lift app: { Error: Cannot find module 'lodash/assign'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/circleci/repo/node_modules/sails-hook-swagger-generator/build/lib/generators.js:36:32)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/circleci/repo/node_modules/sails-hook-swagger-generator/build/lib/swagger-doc.js:51:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32) code: 'MODULE_NOT_FOUND' }
```

**Comment by danielsharvey** [comment]
It looks like an error - the `lodash/assign` module is required from `lib/generators.js` but `lodash` is only included as a DEV dependency. 

Will look to fix.

**Comment by maximilianmeier** [comment]
awesome thank you 👍
